name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test

  clojars-release:

    runs-on: ubuntu-latest

    needs:
      - test

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Clojars
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
      run: lein deploy
