name: Tests

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: DeLaGuardo/setup-clojure@13.1
      with:
        lein: latest
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
